# Generated by Django 2.1.7 on 2019-04-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unique_id',
            field=models.CharField(default='', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
